version: '3.8'
services:
  app:
    image: fubuki:1.0
    volumes:
      - /mnt/storage:/app/storage

    ports:
      - "2000:2000"

    tty: true

    deploy:
      resources:
        limits:
          memory: 300M

networks:
  default:
    driver: bridge
    external: true